import VerticalMenu from '@/components/VerticalMenu';
import LoadingScreen from '@/components/LoadingScreen';
import { TweetProvider } from '@/contexts/tweetsContext';
import RightBar from '@/components/RightBar';

export const metadata = {
  title: 'X. es lo que esta pasando / X',
  description: 'Generated by Next.js',
  icons: {
    icon: '/X_icon_white.png',
    apple: '/X_icon_white.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <div className="flex h-screen overflow-hidden">
      <TweetProvider>
        {/* Espacio lateral izquierdo opcional */}
        <div className="sticky top-0 flex max-w-[100] flex-1 items-start justify-end p-3 pr-4 md:flex">
          <VerticalMenu></VerticalMenu>
        </div>

        {/* Contenedor central */}
        <div className="flex flex-2 overflow-auto">
          {/* Contenido principal */}
          <main className="flex w-full max-w-[600px] flex-col bg-white">{children}</main>

          {/* Espacio lateral derecho opcional */}
          <div className="hidden w-full flex-1 md:flex">
            <RightBar></RightBar>
          </div>
        </div>
        <LoadingScreen></LoadingScreen>
      </TweetProvider>
    </div>
  );
}
