import Header from '@/components/Header';
import VerticalMenu from '@/components/VerticalMenu';
import LoginBar from '@/components/LoginBar';
import { UserProvider } from '@/contexts/userContext';

export const metadata = {
  title: 'X. es lo que esta pasando / X',
  description: 'Generated by Next.js',
  icons: {
    icon: '/X_icon_white.png',
    apple: '/X_icon_white.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <div className="flex h-screen overflow-hidden">
      {/* Espacio lateral izquierdo opcional */}
      <div className="sticky top-0 flex max-w-[100] flex-1 items-start justify-end p-3 pr-4 md:flex">
        <VerticalMenu></VerticalMenu>
      </div>

      {/* Contenedor central */}
      <div className="flex flex-2 overflow-auto">
        {/* Contenido principal */}
        <main className="flex w-full max-w-[600px] flex-col bg-white">{children}</main>

        {/* Espacio lateral derecho opcional */}
        <div className="hidden w-full flex-1 p-4 md:flex">
          {/* Aquí puedes poner contenido adicional opcional */}
        </div>
      </div>
    </div>
  );
}
